columnSuffix: null
handle: bannerColor
instructions: null
name: 'Banner Color'
searchable: false
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
