columnSuffix: null
handle: featuredTestimonial
instructions: null
name: 'Featured Testimonial'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
