columnSuffix: null
handle: source
instructions: null
name: Source
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - LinkedIn
        -
          - value
          - linkedin
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Email
        -
          - value
          - email
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Google Review'
        -
          - value
          - googleReview
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Other
        -
          - value
          - other
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
