defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0b3b6b99-6111-4093-b357-fab0e9e75f80 # Timeline Item
handle: timelineItem
maxAuthors: 1
minAuthors: 1
name: 'Timeline Item'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  3dc07e65-4aa3-4322-9db5-5858b5be36a0: # Myles Pitfield | Portfolio
    enabledByDefault: true
    hasUrls: true
    template: timelineItem/_entry.twig
    uriFormat: 'timelineItem/{slug}'
type: channel
